# Generated by Django 2.2.4 on 2019-08-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'A lot of Subscriber'},
        ),
    ]
