# Generated by Django 2.2.4 on 2019-08-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190830_1335'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInOrderOrder',
            new_name='ProductInOrder',
        ),
    ]
